// Generated by tools/build-browser-engine.js. Do not edit directly.
(function (global) {
  "use strict";
  const NEGATIVE_MOODS = new Set(["sad", "anxious", "tired", "angry"]);
  
  const MOOD_LEVELS = {
    happy: 5,
    calm: 4,
    anxious: 3,
    sad: 2,
    tired: 2,
    angry: 2
  };
  
  const SCORE_LIMITS = {
    mood: 60,
    sleep: 18,
    steps: 14,
    social: 12,
    intervention: 8
  };
  
  const SIGNAL_KEYS = ["mood", "sleep", "steps", "social"];
  
  const SIGNAL_LABELS = {
    mood: "情绪",
    sleep: "睡眠",
    steps: "活动",
    social: "连接"
  };
  
  const DANGER_PATTERNS = [
    { re: /自[杀傷伤]|自杀/, level: "critical", tag: "direct-self-harm" },
    { re: /伤害\s*(自己|自身|我)/, level: "critical", tag: "self-harm-ideation" },
    { re: /自残/, level: "critical", tag: "self-injury" },
    { re: /不想活|不想[再在]?活|活不下去|活着.*累|活着.*痛苦/, level: "critical", tag: "death-wish" },
    { re: /想[要去]?死|想消失|想[从]?[这這]个世界上?消失/, level: "critical", tag: "disappear-or-die" },
    { re: /没有意义|毫无意义|活着.*没有.*意义/, level: "high", tag: "meaninglessness" },
    { re: /撑不住|撑不下去|受不了了|忍不了了/, level: "high", tag: "cannot-cope" },
    { re: /绝望|看不到希望|没有任何希望/, level: "high", tag: "hopelessness" },
    { re: /不想[存在存]在|想要结束/, level: "high", tag: "ending" },
    { re: /解脱|一了百了|不如[死消失]/, level: "high", tag: "implicit-ending" },
    { re: /留[不没]?住|没有人在乎|没人.*在乎/, level: "medium", tag: "isolation" }
  ];
  
  const SAFE_PHRASES = [
    /不想活在.{0,15}里/,
    /不想活[着得].{0,15}但是/,
    /不想活[着得].{0,15}不过/,
    /活着.{0,15}[但虽].{0,15}还/,
    /撑不住.{0,15}[但虽].{0,15}还是/,
    /(?:没有|并无|无)\s*(?:自杀|自伤|自残|伤害\s*(?:自己|自身|我))(?:的)?\s*(?:想法|念头|计划|冲动)/,
    /(?:没有|并无|无)\s*想过\s*(?:自杀|自伤|自残|伤害\s*(?:自己|自身|我))/
  ];
  
  function clamp(value, min, max) {
    return Math.max(min, Math.min(max, value));
  }
  
  function toNumber(value, fallback = 0) {
    const n = Number(value);
    return Number.isFinite(n) ? n : fallback;
  }
  
  function textOf(record = {}) {
    return String(record.note || record.text || record.checkinNote || "");
  }
  
  function moodOf(record = {}) {
    return record.mood || record.et || "calm";
  }
  
  function moodLevelOf(record = {}) {
    return toNumber(record.moodScore ?? record.ii ?? MOOD_LEVELS[moodOf(record)], 3);
  }
  
  function sleepOf(record = {}) {
    return toNumber(record.sleepHours ?? record.sleep, 0);
  }
  
  function stepsOf(record = {}) {
    return toNumber(record.steps ?? record.step, 0);
  }
  
  function socialOf(record = {}) {
    return toNumber(record.socialScore ?? record.sc, 0);
  }
  
  function signalValueOf(record = {}, key) {
    if (key === "mood") return moodLevelOf(record);
    if (key === "sleep") return sleepOf(record);
    if (key === "steps") return stepsOf(record);
    if (key === "social") return socialOf(record);
    return null;
  }
  
  function signalPresent(record = {}, key) {
    if (key === "mood") return record.mood != null || record.et != null || record.moodScore != null || record.ii != null;
    if (key === "sleep") return record.sleepHours != null || record.sleep != null;
    if (key === "steps") return record.steps != null || record.step != null;
    if (key === "social") return record.socialScore != null || record.sc != null;
    return false;
  }
  
  function signalSourceOf(record = {}, key) {
    const source = record.signalSources?.[key] || record.dataSources?.[key];
    if (source) return source;
    if (record.entryType === "device" || record.dataInputMode === "device") return "device";
    if (record.dataInputMode === "manual-web" || record.dataInputMode === "manual") return "manual";
    return record.dataSource || "self-report";
  }
  
  function dataCompletenessOf(record = {}) {
    const missing = [];
    const sources = {};
    let available = 0;
    SIGNAL_KEYS.forEach((key) => {
      if (signalPresent(record, key)) available += 1;
      else missing.push(key);
      sources[key] = signalSourceOf(record, key);
    });
    const required = SIGNAL_KEYS.length;
    const ratio = required ? available / required : 0;
    return {
      available,
      required,
      ratio,
      percent: Math.round(ratio * 100),
      missing,
      sources
    };
  }
  
  function signalSnapshot(record = {}) {
    return Object.fromEntries(SIGNAL_KEYS.map((key) => {
      const item = {
        signal: key,
        value: signalPresent(record, key) ? signalValueOf(record, key) : null,
        present: signalPresent(record, key),
        source: signalSourceOf(record, key)
      };
      return [key, item];
    }));
  }
  
  function normalizeRecords(records) {
    return Array.isArray(records) ? records : [];
  }
  
  function unique(list) {
    const out = [];
    for (const item of list) {
      if (item && !out.includes(item)) out.push(item);
    }
    return out;
  }
  
  function calculateRecoveryScore(record, completedInterventions = []) {
    record = record || {};
    const moodKey = moodOf(record);
    const moodLevel = MOOD_LEVELS[moodKey] || 3;
    const sleepHours = sleepOf(record);
    const steps = stepsOf(record);
    const socialScore = socialOf(record);
    const completed = completedInterventions.length ||
      (Array.isArray(record.completedInterventions) ? record.completedInterventions.length : 0);
  
    const breakdown = {
      mood: clamp(moodLevel * 12, 0, SCORE_LIMITS.mood),
      sleep: clamp(Math.round((sleepHours / 8) * SCORE_LIMITS.sleep), 0, SCORE_LIMITS.sleep),
      steps: clamp(Math.round((steps / 8000) * SCORE_LIMITS.steps), 0, SCORE_LIMITS.steps),
      social: clamp(Math.round((socialScore / 100) * SCORE_LIMITS.social), 0, SCORE_LIMITS.social),
      intervention: completed > 0 ? SCORE_LIMITS.intervention : 0
    };
  
    const total = clamp(
      breakdown.mood + breakdown.sleep + breakdown.steps + breakdown.social + breakdown.intervention,
      0,
      100
    );
  
    const dataCompleteness = dataCompletenessOf(record);
    const presentSignals = SIGNAL_KEYS.filter((key) => signalPresent(record, key));
    const referenceRawTotal = presentSignals.reduce((sum, key) => sum + breakdown[key], 0);
    const referenceMax = presentSignals.reduce((sum, key) => sum + SCORE_LIMITS[key], 0);
    const referenceScore = referenceMax ? Math.round((referenceRawTotal / referenceMax) * 100) : null;
    const contributions = SIGNAL_KEYS.map((key) => ({
      signal: key,
      label: SIGNAL_LABELS[key],
      value: signalPresent(record, key) ? signalValueOf(record, key) : null,
      score: breakdown[key],
      max: SCORE_LIMITS[key],
      present: signalPresent(record, key),
      source: dataCompleteness.sources[key],
      reason: signalPresent(record, key)
        ? `${SIGNAL_LABELS[key]}已经算进这次记录`
        : `${SIGNAL_LABELS[key]}还没填`
    }));
  
    return {
      total,
      referenceScore,
      referenceRawTotal,
      referenceMax,
      referenceSignalCount: presentSignals.length,
      referenceSignalRequired: SIGNAL_KEYS.length,
      breakdown,
      contributions,
      dataCompleteness,
      missingSignals: dataCompleteness.missing,
      confidence: dataCompleteness.ratio >= 0.75 ? "medium" : "low",
      availableMax: 100,
      explanation:
        `情绪 ${breakdown.mood} 分、睡眠 ${breakdown.sleep} 分、步数 ${breakdown.steps} 分、` +
        `社交 ${breakdown.social} 分、干预 ${breakdown.intervention} 分，合成当前恢复指数。没填的项目不会被当成 0 分。`
    };
  }
  
  function explainRecoveryScore(scoreResult) {
    const b = scoreResult.breakdown;
    return `恢复指数 ${scoreResult.total}：情绪 ${b.mood}、睡眠 ${b.sleep}、步数 ${b.steps}、社交 ${b.social}、干预 ${b.intervention}。`;
  }
  
  const SAFE_ACTIONS = ["breathe", "walk", "focus", "journal", "sleep", "friend", "help"];
  const ORDINARY_ACTIONS = ["breathe", "walk", "focus", "journal", "sleep", "friend", "self_check", "ordinary_intervention", "companion", "bottle"];
  const CRISIS_HISTORY_WINDOW_MS = 7 * 24 * 60 * 60 * 1000;
  const ABSOLUTE_SLEEP_FLOOR_HOURS = 4.5;
  const REPEATED_NEGATIVE_WINDOW_COUNT = 3;
  
  function riskShape({
    riskCode,
    mode,
    level,
    tag,
    reason,
    desc,
    evidence,
    shouldRecommendSelfHelp,
    dataCompleteness,
    records
  }) {
    return {
      riskCode,
      risk: level,
      level,
      mode,
      tag,
      reason,
      desc,
      evidence,
      explanation: reason,
      allowedActions: mode === "help" ? ["help"] : mode === "ask" ? ["checkin", "ask"] : SAFE_ACTIONS,
      blockedActions: mode === "help" ? [...ORDINARY_ACTIONS, "checkin", "ask"] : mode === "ask" ? [...ORDINARY_ACTIONS, "help"] : [],
      shouldRecommendSelfHelp,
      dataCompleteness,
      baselineStatus: records.length >= 2 ? "ready" : "cold_start",
      confidence: records.length >= 5 ? "high" : records.length >= 2 ? "medium" : "low",
      policyVersion: "strategy-v1"
    };
  }
  
  /**
   * 检测文本中的危机信号
   * @param {string} text - 用户输入文本
   * @returns {{ hasDanger: boolean, matchedPattern: string|null, level: string|null }}
   */
  function hasDangerSignal(text) {
    let normalized = text.toLowerCase().trim();
  
    // 只移除安全短语片段，再继续扫描剩余文本，避免一句话里还有真实危机信号时被整体放过。
    for (const safe of SAFE_PHRASES) {
      normalized = normalized.replace(safe, " ");
    }
  
    // 检查危险模式
    for (const { re, level } of DANGER_PATTERNS) {
      if (re.test(normalized)) {
        return { hasDanger: true, matchedPattern: re.source, level };
      }
    }
    
    return { hasDanger: false, matchedPattern: null, level: null };
  }
  
  function recordTimestamp(record) {
    const raw = record?.createdAt ?? record?.timestamp ?? record?.at ?? record?.t;
    const timestamp = new Date(raw).getTime();
    return Number.isFinite(timestamp) ? timestamp : null;
  }
  
  function crisisText(records, currentText, now, options = {}) {
    const windowStart = now - CRISIS_HISTORY_WINDOW_MS;
    const includeHistoricalCrisis = options.includeHistoricalCrisis !== false;
    const historyAfter = Number.isFinite(new Date(options.historyAfter || "").getTime())
      ? new Date(options.historyAfter).getTime()
      : null;
    const historical = includeHistoricalCrisis
      ? records.filter((record) => {
        const timestamp = recordTimestamp(record);
        if (timestamp === null) return false;
        return timestamp >= windowStart && timestamp <= now && (historyAfter === null || timestamp > historyAfter);
      }).map(textOf)
      : [];
    const latest = records[records.length - 1];
    const latestTimestamp = recordTimestamp(latest);
    const latestIsCurrent = latestTimestamp === null || (
      latestTimestamp >= windowStart &&
      latestTimestamp <= now &&
      (historyAfter === null || latestTimestamp > historyAfter)
    );
    if (currentText) historical.push(String(currentText));
    else if (latestIsCurrent) historical.push(textOf(latest));
    return historical.join(" ");
  }
  
  function recentNegativeCount(records) {
    return normalizeRecords(records).slice(-4).filter((record) => NEGATIVE_MOODS.has(moodOf(record))).length;
  }
  
  function lowSleepDays(records) {
    return normalizeRecords(records).slice(-4).filter((record) => signalPresent(record, "sleep") && sleepOf(record) < 6).length;
  }
  
  function assessRisk(records, currentText = "", options = {}) {
    const safeRecords = normalizeRecords(records);
    const latest = safeRecords[safeRecords.length - 1] || {};
    const suppliedNow = new Date(options.now ?? Date.now()).getTime();
    const now = Number.isFinite(suppliedNow) ? suppliedNow : Date.now();
    const mergedText = crisisText(safeRecords, currentText, now, options);
    const dataCompleteness = dataCompletenessOf(latest);
    const lowSleep = lowSleepDays(safeRecords);
    const negative = recentNegativeCount(safeRecords);
    const absoluteLowSleep = signalPresent(latest, "sleep") && sleepOf(latest) <= ABSOLUTE_SLEEP_FLOOR_HOURS;
  
    const dangerResult = hasDangerSignal(mergedText);
    if (dangerResult.hasDanger) {
      return riskShape({
        riskCode: "high",
        mode: "help",
        level: "高风险",
        tag: "优先求助",
        reason: `文本中出现危机信号（${dangerResult.level}级），停止普通自助建议，优先连接热线、老师、家人或专业资源。`,
        desc: "文本中出现危机信号时，心晴会先停下普通自助建议，优先展示热线、老师、家人和专业机构入口。",
        evidence: [`Safety Gate: ${dangerResult.level}`, `pattern: ${dangerResult.matchedPattern}`],
        shouldRecommendSelfHelp: false,
        dataCompleteness,
        records: safeRecords
      });
    }
  
    if (dataCompleteness.available < 2 && !absoluteLowSleep && lowSleep < 3 && negative < REPEATED_NEGATIVE_WINDOW_COUNT) {
      return riskShape({
        riskCode: "insufficient",
        mode: "ask",
        level: "数据不足",
        tag: "先补充记录",
        reason: "有效信号还不够建立个人基线，请先补充一条记录。",
        desc: "记录不足时，心晴不会给出普通行动建议，先把个人节奏记录完整。",
        evidence: ["有效信号少于 2 项，个人基线仍在建立"],
        shouldRecommendSelfHelp: false,
        dataCompleteness,
        records: safeRecords
      });
    }
  
    if (absoluteLowSleep || lowSleep >= 3 || negative >= REPEATED_NEGATIVE_WINDOW_COUNT) {
      const evidence = [];
      if (absoluteLowSleep) evidence.push(`当前睡眠不高于 ${ABSOLUTE_SLEEP_FLOOR_HOURS} 小时的绝对关注阈值`);
      if (lowSleep >= 3) evidence.push(`近 4 次记录中 ${lowSleep} 次睡眠低于 6 小时`);
      if (negative >= 3) evidence.push(`近 4 次记录中 ${negative} 次为负向状态`);
      return riskShape({
        riskCode: "medium",
        mode: "action",
        level: "中度关注",
        tag: "建议连接他人",
        reason: "最近低睡眠或负面状态连续出现，建议联系可信任的人或校内支持资源。",
        desc: "本周低睡眠或负面状态连续出现，心晴会优先推荐低负担行动，并提示联系可信任的人。",
        evidence,
        shouldRecommendSelfHelp: true,
        dataCompleteness,
        records: safeRecords
      });
    }
  
    if (NEGATIVE_MOODS.has(moodOf(latest))) {
      return riskShape({
        riskCode: "normal",
        mode: "action",
        level: "普通波动",
        tag: "先做轻干预",
        reason: "当前更像日常压力波动，可先完成一个低负担行动。",
        desc: "当前更像日常压力波动，建议先完成呼吸、散步、记录或睡前放松中的一步。",
        evidence: [`当前情绪: ${moodOf(latest)}`],
        shouldRecommendSelfHelp: true,
        dataCompleteness,
        records: safeRecords
      });
    }
  
    return riskShape({
      riskCode: "stable",
      mode: "action",
      level: "稳定观察",
      tag: "保持记录",
      reason: "当前状态较平稳，继续保持记录和节奏观察。",
      desc: "当前状态较平稳，心晴会继续记录节奏变化，提醒你维持睡眠和连接感。",
      evidence: ["未触发危机词、连续低睡眠或连续负面状态规则"],
      shouldRecommendSelfHelp: true,
      dataCompleteness,
      records: safeRecords
    });
  }
  
  // 向后兼容：导出危险模式供外部使用
  const dangerWords = DANGER_PATTERNS.map(({ re }) => re.source);
  const dangerPatterns = DANGER_PATTERNS;
  const safePhrases = SAFE_PHRASES;
  
  const PATHS = {
    anxious: ["breathe", "walk", "journal"],
    sad: ["breathe", "friend", "sleep"],
    tired: ["sleep", "breathe", "focus"],
    angry: ["breathe", "walk", "friend"],
    calm: ["focus", "journal", "walk"],
    happy: ["focus", "journal", "walk"]
  };
  
  const PATH_REASONS = {
    anxious: "先降低生理唤醒，再把注意力从压力源中移开。",
    sad: "先稳定状态，再建立连接，避免独自承受。",
    tired: "优先恢复身体电量，再恢复掌控感。",
    angry: "先把身体带离情绪中心，再表达。",
    calm: "顺势完成小目标，保留稳定节奏。",
    happy: "利用较好状态推进小目标，并留下正向记录。"
  };
  
  function completePath(chain, mood) {
    const base = PATHS[mood] || PATHS.calm;
    const fallback = ["breathe", "journal", "friend", "sleep", "walk", "focus"];
    return unique([...chain, ...base, ...fallback]).slice(0, 3);
  }
  
  function recommendPath(record, risk) {
    record = record || {};
    if (risk && risk.level === "高风险") {
      return {
        path: ["help"],
        reason: "高风险场景停止普通自助干预，优先进入求助入口。",
        reasons: ["出现危机信号"]
      };
    }
    if (risk && (risk.mode === "ask" || risk.riskCode === "insufficient" || risk.level === "数据不足")) {
      return {
        path: ["ask"],
        reason: "记录还不够，先补充一条记录再判断下一步。",
        reasons: ["个人基线仍在建立"]
      };
    }
  
    const mood = moodOf(record);
    const sleepHours = sleepOf(record);
    const socialScore = toNumber(record.socialScore ?? record.sc, 50);
    const energyLevel = record.energyLevel || "mid";
    const connectionNeed = record.connectionNeed || "ok";
    const reasons = [];
    let chain = (PATHS[mood] || PATHS.calm).slice();
  
    if (connectionNeed === "need" || socialScore < 25) {
      chain = ["friend", ...chain];
      reasons.push(connectionNeed === "need" ? "用户主动表达需要连接" : "社交连接偏低");
    } else if (connectionNeed === "avoid") {
      chain = [...chain.filter((id) => id !== "friend"), "friend"];
      reasons.push("用户暂时不想联系别人");
    }
  
    if (sleepHours > 0 && sleepHours < 5.2) {
      chain = ["sleep", "breathe", "journal", ...chain.filter((id) => id !== "focus")];
      reasons.push("睡眠明显不足");
    } else if (sleepHours > 0 && sleepHours < 6) {
      chain = mood === "tired" ? ["sleep", "breathe", ...chain] : ["breathe", "sleep", ...chain];
      reasons.push("睡眠低于 6 小时");
    }
  
    if (energyLevel === "low") {
      chain = ["breathe", "journal", "sleep", ...chain.filter((id) => id !== "focus")];
      reasons.push("精力偏低");
    } else if (energyLevel === "high" && ["happy", "calm"].includes(mood)) {
      chain = ["focus", ...chain];
      reasons.push("精力较高");
    }
  
    if (mood === "angry") {
      chain = ["walk", "breathe", ...chain];
      reasons.push("烦躁状态更适合先离开原地");
    }
  
    const path = completePath(chain, mood);
    return {
      path,
      reason: reasons.length
        ? `根据${reasons.join("、")}调整推荐顺序。`
        : PATH_REASONS[mood] || PATH_REASONS.calm,
      reasons: reasons.length ? unique(reasons) : ["当前状态较平稳"]
    };
  }
  
  const interventionLabels = {
    breathe: "先把身体降下来",
    walk: "离开原地 10 分钟",
    journal: "把脑子里的话倒出来",
    friend: "让一个人知道你",
    sleep: "今晚先收住",
    focus: "只做一件小事",
    help: "打开求助入口"
  };
  
  const POLICY_PACKAGE = Object.freeze({
    id: "mindpulse-safety-core",
    version: "2026.08.04.1",
    schemaVersion: 1,
    sourceModules: ["signals", "risk-assessment", "recommendation"]
  });
  
  function hash(value) {
    let valueHash = 2166136261;
    for (const character of value) {
      valueHash ^= character.charCodeAt(0);
      valueHash = Math.imul(valueHash, 16777619);
    }
    return `fnv1a-${(valueHash >>> 0).toString(16).padStart(8, "0")}`;
  }
  
  const POLICY_PACKAGE_HASH = hash(JSON.stringify(POLICY_PACKAGE));
  
  function evaluatePolicyCore(records = [], currentText = "", options = {}) {
    const safeRecords = Array.isArray(records) ? records : [];
    const latest = safeRecords.at(-1) || {};
    const risk = assessRisk(safeRecords, currentText, options);
    const recommendation = recommendPath(latest, risk);
    let path = risk.riskCode === "insufficient" ? ["checkin"] : recommendation.path;
    if (risk.riskCode === "medium" && !path.includes("friend")) path = ["friend", ...path].slice(0, 3);
    return {
      policyId: POLICY_PACKAGE.id,
      policyVersion: POLICY_PACKAGE.version,
      policyHash: POLICY_PACKAGE_HASH,
      riskCode: risk.riskCode,
      mode: risk.mode,
      allowedActions: risk.allowedActions || [],
      blockedActions: risk.blockedActions || [],
      path,
      evidence: risk.evidence || []
    };
  }
  
  function evaluateIosPolicyCore(records = [], currentText = "", options = {}) {
    return evaluatePolicyCore(records, currentText, options);
  }
  
  const ACTION_FEEDBACK_MIN_DELAY_MS = 10 * 60 * 1000;
  const ACTION_FEEDBACK_MAX_DELAY_MS = 30 * 60 * 1000;
  const ACTION_FEEDBACK_CLOCK_SKEW_MS = 2 * 60 * 1000;
  
  function asTime(value) {
    const time = new Date(value || "").getTime();
    return Number.isFinite(time) ? time : null;
  }
  
  function isHighRisk(risk) {
    return risk?.riskCode === "high" || risk?.riskMode === "help" || risk?.mode === "help" || risk?.level === "high";
  }
  
  function isInsufficient(risk) {
    return risk?.riskCode === "insufficient" || risk?.riskMode === "ask" || risk?.mode === "ask";
  }
  
  function feedbackWindowFor(completion) {
    const completedAt = asTime(completion?.createdAt);
    if (completedAt === null) return null;
    return {
      opensAt: new Date(completedAt + ACTION_FEEDBACK_MIN_DELAY_MS).toISOString(),
      closesAt: new Date(completedAt + ACTION_FEEDBACK_MAX_DELAY_MS).toISOString()
    };
  }
  
  function isEligibleFeedbackEvent(event) {
    if (!event || event.eventType !== "outcome-feedback") return false;
    if (!event.feedbackCompletionEventId || event.eligibleForLearning !== true || event.feedbackTimingValid !== true) return false;
    if (event.learningExclusionReason || !["better", "same", "worse"].includes(event.outcome)) return false;
    if (isHighRisk(event) || isInsufficient(event)) return false;
    if (event.feedbackContext?.dataMode && event.feedbackContext.dataMode !== "real-trial") return false;
    return true;
  }
  
  function feedbackEligibilityFor({ completion, feedbackEvents = [], outcome, now = Date.now(), currentRisk, currentRecord }) {
    const window = feedbackWindowFor(completion);
    const nowTime = typeof now === "number" ? now : asTime(now);
    const completedAt = asTime(completion?.createdAt);
    const result = {
      eligible: false,
      timingValid: false,
      exclusionReason: "clock-invalid",
      feedbackDueAt: window?.opensAt,
      feedbackExpiresAt: window?.closesAt,
      contextChanged: false
    };
  
    if (nowTime === null || completedAt === null || !window) return result;
    if (nowTime < completedAt - ACTION_FEEDBACK_CLOCK_SKEW_MS) return result;
    if (nowTime < completedAt + ACTION_FEEDBACK_MIN_DELAY_MS) return { ...result, timingValid: true, exclusionReason: "too-early" };
    if (nowTime > completedAt + ACTION_FEEDBACK_MAX_DELAY_MS) return { ...result, timingValid: true, exclusionReason: "too-late" };
  
    const contextChanged = Boolean(
      completion?.contextAfter?.id && currentRecord?.id && completion.contextAfter.id !== currentRecord.id
    );
    const alreadyRecorded = Array.isArray(feedbackEvents) && feedbackEvents.some((event) => (
      event?.eventType === "outcome-feedback" && event.feedbackCompletionEventId === completion?.id
    ));
    const completionRisk = { riskCode: completion?.riskCode, riskMode: completion?.riskMode };
    const syntheticData = completion?.feedbackContext?.dataMode && completion.feedbackContext.dataMode !== "real-trial";
  
    if (outcome === "skipped") return { ...result, timingValid: true, exclusionReason: "skipped", contextChanged };
    if (alreadyRecorded) return { ...result, timingValid: true, exclusionReason: "duplicate", contextChanged };
    if (isHighRisk(completionRisk) || isHighRisk(currentRisk)) return { ...result, timingValid: true, exclusionReason: "high-risk", contextChanged };
    if (isInsufficient(completionRisk) || isInsufficient(currentRisk)) return { ...result, timingValid: true, exclusionReason: "insufficient-data", contextChanged };
    if (syntheticData) return { ...result, timingValid: true, exclusionReason: "synthetic-data", contextChanged };
    if (contextChanged) return { ...result, timingValid: true, exclusionReason: "context-changed", contextChanged };
    if (!["better", "same", "worse"].includes(outcome)) return { ...result, timingValid: true, exclusionReason: "skipped", contextChanged };
  
    return { ...result, eligible: true, timingValid: true, exclusionReason: undefined, contextChanged: false };
  }
  
  const PERSONALIZATION_MIN_SAFE_FEEDBACK = 3;
  
  function percentDelta(current, baseline) {
    if (current === null || baseline === null || baseline === 0) return null;
    return Math.round(((current - baseline) / baseline) * 100);
  }
  
  function average(values, fallback = null) {
    if (!values.length) return fallback;
    return values.reduce((sum, value) => sum + value, 0) / values.length;
  }
  
  function round(value, digits = 1) {
    return Number(Number(value).toFixed(digits));
  }
  
  function confidenceFor(historyRecords, dataCompleteness, baselineReady) {
    const historyScore = Math.min(1, historyRecords / 5);
    const readinessScore = baselineReady ? 1 : Math.min(0.75, historyRecords / 3);
    const score = round(historyScore * 0.55 + dataCompleteness.ratio * 0.3 + readinessScore * 0.15, 2);
    const confidence = score >= 0.75 ? "high" : score >= 0.45 ? "medium" : "low";
    return {
      score,
      confidence,
      text: confidence === "high" ? "较高" : confidence === "medium" ? "中等" : "较低"
    };
  }
  
  function calculatePersonalBaseline(records) {
    const safeRecords = normalizeRecords(records);
    const latest = safeRecords[safeRecords.length - 1] || {};
    let history = safeRecords.slice(0, -1).slice(-6);
    if (!history.length) history = safeRecords.slice(0, -1);
  
    const dataCompleteness = dataCompletenessOf(latest);
    const signals = Object.fromEntries(SIGNAL_KEYS.map((key) => {
      const values = history
        .filter((record) => signalPresent(record, key))
        .map((record) => signalValueOf(record, key));
      const current = signalPresent(latest, key) ? signalValueOf(latest, key) : null;
      const baseline = average(values, current);
      const delta = current === null || baseline === null ? null : round(current - baseline, key === "steps" ? 0 : 1);
      const relativeDelta = percentDelta(current, baseline);
      const ready = values.length >= 2 && baseline !== null;
      return [key, {
        baseline,
        current,
        delta,
        relativeDelta,
        sampleCount: values.length,
        ready,
        present: current !== null,
        source: current === null ? "unknown" : signalSourceOf(latest, key),
        explanation: ready
          ? `${SIGNAL_LABELS[key]}基于 ${values.length} 次过往记录比较`
          : `${SIGNAL_LABELS[key]}还在建立个人基线`
      }];
    }));
    const readySignalCount = Object.values(signals).filter((signal) => signal.ready).length;
    const baselineReady = history.length >= 2 && readySignalCount >= 2;
  
    const base = {
      days: history.length,
      mood: average(history.filter((record) => signalPresent(record, "mood")).map((record) => signalValueOf(record, "mood")), signalValueOf(latest, "mood")),
      sleep: average(history.filter((record) => signalPresent(record, "sleep")).map((record) => signalValueOf(record, "sleep")), signalValueOf(latest, "sleep")),
      steps: average(history.filter((record) => signalPresent(record, "steps")).map((record) => signalValueOf(record, "steps")), signalValueOf(latest, "steps")),
      social: average(history.filter((record) => signalPresent(record, "social")).map((record) => signalValueOf(record, "social")), signalValueOf(latest, "social"))
    };
  
    const current = {
      mood: signals.mood.current,
      sleep: signals.sleep.current,
      steps: signals.steps.current,
      social: signals.social.current
    };
  
    const delta = {
      mood: current.mood === null || base.mood === null ? null : round(current.mood - base.mood, 1),
      sleepPct: percentDelta(current.sleep, base.sleep),
      stepsPct: percentDelta(current.steps, base.steps),
      social: current.social === null || base.social === null ? null : round(current.social - base.social, 0)
    };
  
    const flags = [];
    if (signals.sleep.ready && delta.sleepPct <= -25) flags.push(`睡眠低于个人基线 ${Math.abs(delta.sleepPct)}%`);
    if (signals.steps.ready && delta.stepsPct <= -40) flags.push(`活动低于个人基线 ${Math.abs(delta.stepsPct)}%`);
    if (signals.social.ready && delta.social <= -20) flags.push(`连接感低于个人基线 ${Math.abs(delta.social)} 点`);
    if (signals.mood.ready && delta.mood <= -1) flags.push(`情绪低于个人基线 ${Math.abs(delta.mood).toFixed(1)} 级`);
  
    const level = !baselineReady ? "数据不足" : flags.length >= 2 ? "明显偏离" : flags.length === 1 ? "轻度偏离" : "接近基线";
    const confidence = confidenceFor(history.length, dataCompleteness, baselineReady);
    return {
      base,
      delta,
      flags,
      level,
      title: level === "数据不足"
        ? "先记录几次，再建立你的平时节奏"
        : level === "接近基线"
          ? "今天接近自己的正常节奏"
          : (level === "轻度偏离" ? "今天有一个信号偏离基线" : "今天多个信号偏离个人基线"),
      desc: level === "数据不足"
        ? "现在的记录还不够比较个人基线，先补充几次，不给出假精确结论。"
        : flags.length
        ? `${flags.join("；")}。这是按个人历史节奏判断，不是和别人比较。`
        : "睡眠、活动和连接感没有明显低于你的近几天基线。",
      coldStart: safeRecords.length < 2,
      baselineReady,
      historyRecords: history.length,
      readySignalCount,
      confidence: confidence.confidence,
      confidenceText: confidence.text,
      confidenceScore: confidence.score,
      dataCompleteness,
      signals
    };
  }
  
  function summarizeInterventionFeedback(events = [], interventionStats = {}) {
    const grouped = {};
    const safeEvents = Array.isArray(events) ? events : [];
    safeEvents.forEach((event) => {
      if (!isEligibleFeedbackEvent(event)) return;
      const actionId = String(event.interventionId || event.actionId || event.id || "").trim();
      if (!actionId || actionId === "help") return;
      if (event.riskMode === "HIGH_RISK" || event.riskLevel === "高风险" || event.riskCode === "high" || event.mode === "help") return;
      const current = grouped[actionId] || { count: 0, totalOutcome: 0 };
      const outcomeValue = event.outcome === "better" ? 1 : event.outcome === "worse" ? -1 : 0;
      current.count += 1;
      current.totalOutcome += outcomeValue;
      current.avgOutcome = Math.round(current.totalOutcome / current.count * 10) / 10;
      current.eligible = current.count >= PERSONALIZATION_MIN_SAFE_FEEDBACK;
      current.confidence = current.count >= 6 ? "high" : current.eligible ? "medium" : "low";
      current.confidenceText = current.count >= 6 ? "观察较稳定" : current.eligible ? "刚达到可比较样本" : "还在积累样本";
      grouped[actionId] = current;
    });
    if (!safeEvents.length) return interventionStats?.__meta?.learningSource === "subjective-outcome" ? interventionStats : {};
    return grouped;
  }
  
  function personalizeRecommendation(path, interventionStats = {}, events = []) {
    const feedback = Array.isArray(events) && events.length
      ? summarizeInterventionFeedback(events, interventionStats)
      : interventionStats?.__meta?.learningSource === "subjective-outcome" ? interventionStats : {};
    const status = personalizationStatus(feedback);
    if (!status.formed) return unique(path);
    return unique(path)
      .map((id, index) => {
        const stat = feedback[id];
        const avgOutcome = stat?.avgOutcome ?? (stat?.count ? Number(stat.totalOutcome || 0) / stat.count : 0);
        const boost = stat?.eligible ? Math.min(2.4, stat.count * 0.35) + Math.max(0, avgOutcome) * 0.6 : 0;
        return { id, score: index - boost, avgOutcome, count: stat?.count || 0 };
      })
      .sort((a, b) => a.score - b.score)
      .map((item) => item.id);
  }
  
  function personalizationStatus(stats = {}) {
    const safeFeedbackCount = Object.entries(stats).reduce((sum, [key, stat]) => {
      if (key === "__meta" || !stat || typeof stat !== "object") return sum;
      return sum + Math.max(0, Number(stat.safeCount ?? stat.count) || 0);
    }, 0);
    const eligibleActionCount = Object.entries(stats).reduce((sum, [key, stat]) => (
      key !== "__meta" && stat && typeof stat === "object" && Number(stat.safeCount ?? stat.count) >= PERSONALIZATION_MIN_SAFE_FEEDBACK
        ? sum + 1
        : sum
    ), 0);
    return {
      formed: eligibleActionCount > 0,
      safeFeedbackCount,
      required: PERSONALIZATION_MIN_SAFE_FEEDBACK,
      eligibleActionCount,
      excludedHighRisk: Math.max(0, Number(stats.__meta?.excludedHighRisk) || 0)
    };
  }
  
  function recordSafeFeedback(stats = {}, feedback = {}) {
    const next = Object.fromEntries(Object.entries(stats).map(([key, value]) => [
      key,
      value && typeof value === "object" ? { ...value } : value
    ]));
    next.__meta = { ...(next.__meta || {}) };
    if (feedback.riskMode === "HIGH_RISK" || feedback.riskLevel === "高风险" || feedback.riskCode === "high" || feedback.mode === "help") {
      next.__meta.excludedHighRisk = (Number(next.__meta.excludedHighRisk) || 0) + 1;
      return next;
    }
    const actionId = String(feedback.actionId || "").trim();
    if (!actionId || !["better", "same", "worse"].includes(feedback.outcome)) return next;
    next.__meta.learningSource = "subjective-outcome";
    const current = next[actionId] && typeof next[actionId] === "object" ? next[actionId] : {};
    const count = Math.max(0, Number(current.safeCount ?? current.count) || 0) + 1;
    const outcomeValue = feedback.outcome === "better" ? 1 : feedback.outcome === "worse" ? -1 : 0;
    next[actionId] = {
      ...current,
      count,
      safeCount: count,
      eligible: count >= PERSONALIZATION_MIN_SAFE_FEEDBACK,
      totalOutcome: (Number(current.totalOutcome) || 0) + outcomeValue,
      lastOutcome: feedback.outcome,
      lastAt: feedback.outcomeRecordedAt || new Date().toISOString()
    };
    return next;
  }

  global.MindPulseRules = {
    calculateRecoveryScore: calculateRecoveryScore,
    assessRisk: assessRisk,
    recommendPath: recommendPath,
    evaluatePolicyCore: evaluatePolicyCore,
    policyPackage: POLICY_PACKAGE,
    policyPackageHash: POLICY_PACKAGE_HASH,
    calculatePersonalBaseline: calculatePersonalBaseline,
    personalizeRecommendation: personalizeRecommendation,
    summarizeInterventionFeedback: summarizeInterventionFeedback,
    feedbackEligibilityFor: feedbackEligibilityFor,
    feedbackWindowFor: feedbackWindowFor,
    dataCompletenessOf: dataCompletenessOf,
    signalSnapshot: signalSnapshot,
    signalPresent: signalPresent,
    signalValueOf: signalValueOf,
    signalSourceOf: signalSourceOf,
    SIGNAL_KEYS: SIGNAL_KEYS,
    SIGNAL_LABELS: SIGNAL_LABELS,
    lowSleepDays: lowSleepDays,
    recentNegativeCount: recentNegativeCount,
    hasDangerSignal: hasDangerSignal,
    dangerPatterns: DANGER_PATTERNS,
    safePhrases: SAFE_PHRASES
  };
})(window);
