// Generated by tools/build-browser-engine.js. Do not edit directly.
(function (global) {
  "use strict";
  const NEGATIVE_MOODS = new Set(["sad", "anxious", "tired", "angry"]);
  
  const MOOD_LEVELS = {
    happy: 5,
    calm: 4,
    anxious: 3,
    sad: 2,
    tired: 2,
    angry: 2
  };
  
  const SCORE_LIMITS = {
    mood: 60,
    sleep: 18,
    steps: 14,
    social: 12,
    intervention: 8
  };
  
  const SIGNAL_KEYS = ["mood", "sleep", "steps", "social"];
  
  const SIGNAL_LABELS = {
    mood: "情绪",
    sleep: "睡眠",
    steps: "活动",
    social: "连接"
  };
  
  const DANGER_PATTERNS = [
    { re: /自[杀傷伤]|自杀/, level: "critical", tag: "direct-self-harm" },
    { re: /伤害\s*(自己|自身|我)/, level: "critical", tag: "self-harm-ideation" },
    { re: /自残/, level: "critical", tag: "self-injury" },
    { re: /不想活|不想[再在]?活|活不下去|活着.*累|活着.*痛苦/, level: "critical", tag: "death-wish" },
    { re: /想[要去]?死|想消失|想[从]?[这這]个世界上?消失/, level: "critical", tag: "disappear-or-die" },
    { re: /没有意义|毫无意义|活着.*没有.*意义/, level: "high", tag: "meaninglessness" },
    { re: /撑不住|撑不下去|受不了了|忍不了了/, level: "high", tag: "cannot-cope" },
    { re: /绝望|看不到希望|没有任何希望/, level: "high", tag: "hopelessness" },
    { re: /不想[存在存]在|想要结束/, level: "high", tag: "ending" },
    { re: /解脱|一了百了|不如[死消失]/, level: "high", tag: "implicit-ending" },
    { re: /留[不没]?住|没有人在乎|没人.*在乎/, level: "medium", tag: "isolation" }
  ];
  
  const SAFE_PHRASES = [
    /不想活在.*里/,
    /不想活[着得].*但是/,
    /不想活[着得].*不过/,
    /活着.*[但虽].*还/,
    /撑不住.*[但虽].*还是/,
    /(?:没有|并无|无)\s*(?:自杀|自伤|自残|伤害\s*(?:自己|自身|我))(?:的)?\s*(?:想法|念头|计划|冲动)/,
    /(?:没有|并无|无)\s*想过\s*(?:自杀|自伤|自残|伤害\s*(?:自己|自身|我))/
  ];
  
  function clamp(value, min, max) {
    return Math.max(min, Math.min(max, value));
  }
  
  function toNumber(value, fallback = 0) {
    const n = Number(value);
    return Number.isFinite(n) ? n : fallback;
  }
  
  function textOf(record = {}) {
    return String(record.note || record.text || record.checkinNote || "");
  }
  
  function moodOf(record = {}) {
    return record.mood || record.et || "calm";
  }
  
  function rawMoodLevelOf(record = {}) {
    const explicit = record.moodScore ?? record.ii;
    if (explicit !== undefined && explicit !== null && explicit !== "") {
      const parsed = Number(explicit);
      return Number.isFinite(parsed) ? parsed : null;
    }
    const key = record.mood || record.et;
    return key && MOOD_LEVELS[key] ? MOOD_LEVELS[key] : null;
  }
  
  function rawNumberOf(record, primary, legacy) {
    const value = record[primary] ?? record[legacy];
    if (value === undefined || value === null || value === "") return null;
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : null;
  }
  
  function signalValueOf(record = {}, key) {
    if (key === "mood") return rawMoodLevelOf(record);
    if (key === "sleep") return rawNumberOf(record, "sleepHours", "sleep");
    if (key === "steps") return rawNumberOf(record, "steps", "step");
    if (key === "social") return rawNumberOf(record, "socialScore", "sc");
    return null;
  }
  
  function signalPresent(record = {}, key) {
    const presence = record.signalPresence;
    if (presence && Object.prototype.hasOwnProperty.call(presence, key)) {
      return Boolean(presence[key]);
    }
    const value = signalValueOf(record, key);
    if (value === null || value === undefined || !Number.isFinite(Number(value))) return false;
    if (key === "mood") return Number(value) >= 1 && Number(value) <= 5;
    return Number(value) >= 0;
  }
  
  function signalSourceOf(record = {}, key) {
    const sourceMaps = [record.signalSources, record.dataSources, record.sources];
    for (const sourceMap of sourceMaps) {
      if (sourceMap && typeof sourceMap === "object" && sourceMap[key]) {
        return String(sourceMap[key]);
      }
    }
    if (record.dataInputMode === "manual-web") return "manual";
    if (record.entryType === "device") return "device";
    if (record.dataSource) return String(record.dataSource);
    if (record.entryType === "instant" || record.entryType === "daily") return "self-report";
    return "unknown";
  }
  
  function signalSnapshot(record = {}) {
    return SIGNAL_KEYS.reduce((snapshot, key) => {
      snapshot[key] = {
        value: signalValueOf(record, key),
        present: signalPresent(record, key),
        source: signalSourceOf(record, key),
        label: SIGNAL_LABELS[key]
      };
      return snapshot;
    }, {});
  }
  
  function dataCompletenessOf(record = {}) {
    const signals = signalSnapshot(record);
    const available = SIGNAL_KEYS.filter((key) => signals[key].present);
    const missing = SIGNAL_KEYS.filter((key) => !signals[key].present);
    const ratio = SIGNAL_KEYS.length ? available.length / SIGNAL_KEYS.length : 0;
    return {
      available: available.length,
      required: SIGNAL_KEYS.length,
      ratio,
      percent: Math.round(ratio * 100),
      missing,
      sources: SIGNAL_KEYS.reduce((sources, key) => {
        sources[key] = signals[key].source;
        return sources;
      }, {}),
      signals
    };
  }
  
  function moodLevelOf(record = {}) {
    return toNumber(rawMoodLevelOf(record), 3);
  }
  
  function sleepOf(record = {}) {
    return toNumber(signalValueOf(record, "sleep"), 0);
  }
  
  function stepsOf(record = {}) {
    return toNumber(signalValueOf(record, "steps"), 0);
  }
  
  function socialOf(record = {}) {
    return toNumber(signalValueOf(record, "social"), 0);
  }
  
  function normalizeRecords(records) {
    return Array.isArray(records) ? records : [];
  }
  
  function unique(list) {
    const out = [];
    for (const item of list) {
      if (item && !out.includes(item)) out.push(item);
    }
    return out;
  }
  
  const COMPONENTS = [
    { key: "mood", max: SCORE_LIMITS.mood },
    { key: "sleep", max: SCORE_LIMITS.sleep },
    { key: "steps", max: SCORE_LIMITS.steps },
    { key: "social", max: SCORE_LIMITS.social }
  ];
  
  function componentValue(key, value) {
    if (key === "mood") return clamp(Math.round(Number(value) * 12), 0, SCORE_LIMITS.mood);
    if (key === "sleep") return clamp(Math.round((Number(value) / 8) * SCORE_LIMITS.sleep), 0, SCORE_LIMITS.sleep);
    if (key === "steps") return clamp(Math.round((Number(value) / 8000) * SCORE_LIMITS.steps), 0, SCORE_LIMITS.steps);
    if (key === "social") return clamp(Math.round((Number(value) / 100) * SCORE_LIMITS.social), 0, SCORE_LIMITS.social);
    return 0;
  }
  
  function confidenceFor(ratio) {
    if (ratio >= 0.9) return "high";
    if (ratio >= 0.6) return "medium";
    return "low";
  }
  
  function calculateRecoveryScore(record = {}, completedInterventions = []) {
    const safeRecord = record || {};
    const completed = Array.isArray(completedInterventions)
      ? completedInterventions.length
      : (Array.isArray(safeRecord.completedInterventions) ? safeRecord.completedInterventions.length : 0);
    const data = dataCompletenessOf(safeRecord);
    const breakdown = {
      mood: 0,
      sleep: 0,
      steps: 0,
      social: 0,
      intervention: completed > 0 ? SCORE_LIMITS.intervention : 0
    };
    const contributions = [];
    let availableMax = 0;
    let availableCoreCount = 0;
  
    for (const component of COMPONENTS) {
      const { key, max } = component;
      const present = signalPresent(safeRecord, key);
      const value = present ? signalValueOf(safeRecord, key) : null;
      const score = present ? componentValue(key, value) : 0;
      breakdown[key] = score;
      if (present) {
        availableCoreCount += 1;
        availableMax += max;
      }
      contributions.push({
        signal: key,
        label: SIGNAL_LABELS[key],
        value,
        score,
        max,
        present,
        source: data.sources[key],
        reason: present
          ? `${SIGNAL_LABELS[key]}已经算进这次记录`
          : `${SIGNAL_LABELS[key]}还没填，不会按 0 分计算`
      });
    }
  
    if (availableCoreCount > 0) {
      availableMax += SCORE_LIMITS.intervention;
      contributions.push({
        signal: "intervention",
        label: "行动反馈",
        value: completed,
        score: breakdown.intervention,
        max: SCORE_LIMITS.intervention,
        present: true,
        source: "local-event",
        reason: completed > 0 ? `已经完成 ${completed} 个小行动` : "还没有完成小行动"
      });
    }
  
    const rawTotal = contributions.reduce((sum, item) => sum + (item.present ? item.score : 0), 0);
    const total = availableMax && availableCoreCount > 0
      ? clamp(Math.round((rawTotal / availableMax) * 100), 0, 100)
      : 0;
    const normalizedContributions = contributions.map((item) => ({
      ...item,
      share: item.present && availableMax ? Math.round((item.score / availableMax) * 100) : 0
    }));
    const missingText = data.missing.length ? `还没填：${data.missing.map((key) => SIGNAL_LABELS[key]).join("、")}。` : "主要记录都填好了。";
    const usedText = data.available ? `这次参考了 ${data.available}/${data.required} 项记录。` : "现在还没有足够的记录。";
  
    return {
      total,
      breakdown,
      contributions: normalizedContributions,
      dataCompleteness: data,
      missingSignals: data.missing,
      confidence: confidenceFor(data.ratio),
      availableMax,
      explanation: `${usedText}${missingText}没填的项目不会被当成 0 分。`
    };
  }
  
  function explainRecoveryScore(scoreResult) {
    const b = scoreResult.breakdown || {};
    const missing = scoreResult.missingSignals || [];
    const suffix = missing.length ? ` 缺失信号未按 0 分计入：${missing.join("、")}。` : "";
    return `这次状态分 ${scoreResult.total}：情绪 ${b.mood || 0}、睡眠 ${b.sleep || 0}、活动 ${b.steps || 0}、连接 ${b.social || 0}、行动 ${b.intervention || 0}。${suffix}`;
  }
  
  const ORDINARY_ACTIONS = ["breathe", "walk", "journal", "sleep", "focus", "friend"];
  
  /**
   * 检测文本中的危机信号
   * @param {string} text - 用户输入文本
   * @returns {{ hasDanger: boolean, matchedPattern: string|null, level: string|null }}
   */
  function hasDangerSignal(text) {
    let normalized = String(text || "").toLowerCase().trim();
  
    // 只移除安全短语片段，再继续扫描剩余文本，避免一句话里还有真实危机信号时被整体放过。
    for (const safe of SAFE_PHRASES) {
      normalized = normalized.replace(safe, " ");
    }
  
    // 检查危险模式。
    for (const { re, level } of DANGER_PATTERNS) {
      if (re.test(normalized)) {
        return { hasDanger: true, matchedPattern: re.source, level };
      }
    }
  
    return { hasDanger: false, matchedPattern: null, level: null };
  }
  
  function recentNegativeCount(records) {
    return normalizeRecords(records).slice(-4).filter((record) => {
      return signalPresent(record, "mood") && NEGATIVE_MOODS.has(moodOf(record));
    }).length;
  }
  
  function lowSleepDays(records) {
    return normalizeRecords(records).slice(-4).filter((record) => {
      return signalPresent(record, "sleep") && sleepOf(record) < 6;
    }).length;
  }
  
  function strategy({ riskCode, level, mode, tag, reason, desc, evidence, data, baseline, explanation }) {
    const highRisk = riskCode === "high";
    const dataShortage = riskCode === "insufficient";
    const allowedActions = highRisk
      ? ["help"]
      : dataShortage
        ? ["checkin", "ask"]
        : ["checkin", "light_intervention", "contact_support"];
    const blockedActions = highRisk
      ? [...ORDINARY_ACTIONS, "self_check", "ordinary_intervention"]
      : dataShortage
        ? ["ordinary_intervention", "self_check"]
        : [];
    return {
      riskCode,
      risk: level,
      level,
      mode,
      tag,
      reason,
      desc,
      evidence,
      explanation: explanation || reason,
      allowedActions,
      blockedActions,
      shouldRecommendSelfHelp: !highRisk && !dataShortage,
      dataCompleteness: data,
      baselineStatus: baseline?.status || "unknown",
      confidence: baseline?.confidence || (data.ratio >= 0.75 ? "medium" : "low"),
      policyVersion: "strategy-v1"
    };
  }
  
  function assessRisk(records, currentText = "") {
    const safeRecords = normalizeRecords(records);
    const latest = safeRecords[safeRecords.length - 1] || {};
    const data = dataCompletenessOf(latest);
    const baseline = calculatePersonalBaseline(safeRecords);
    const mergedText = `${textOf(latest)} ${currentText}`;
    const lowSleep = lowSleepDays(safeRecords);
    const negative = recentNegativeCount(safeRecords);
  
    const dangerResult = hasDangerSignal(mergedText);
    if (dangerResult.hasDanger) {
      return strategy({
        riskCode: "high",
        level: "高风险",
        mode: "help",
        tag: "优先求助",
        reason: "文字中出现了需要优先求助的内容。现在先联系热线、老师、家人或身边可信任的人。",
        desc: "这时先停下普通建议，优先找到一个真实的人。",
        evidence: ["需要优先求助", "文字中出现了需要关注的内容"],
        explanation: "现在先联系一个真实的人，普通建议暂时暂停。",
        data,
        baseline
      });
    }
  
    // 冷启动和信号缺失优先于普通波动判断，避免一条负面记录被误读成稳定建议。
    if (!safeRecords.length || data.available < 2 || baseline.status !== "ready") {
      return strategy({
        riskCode: "insufficient",
        level: "数据不足",
        mode: "ask",
        tag: "补充最少记录",
        reason: "现在记录还不够，先补充一点信息，再看看下一步。",
        desc: "先补充最少的一项记录，等更了解你的平时状态后再决定下一步。",
        evidence: [
          `现在已有 ${data.available}/${data.required} 项记录`,
          `过去已有 ${baseline.historyRecords}/${3} 条记录`
        ],
        explanation: "记录还不够，我先不急着下确定结论。",
        data,
        baseline
      });
    }
  
    if (lowSleep >= 3 || negative >= 3) {
      const evidence = [];
      if (lowSleep >= 3) evidence.push(`近 4 次记录中 ${lowSleep} 次睡眠低于 6 小时`);
      if (negative >= 3) evidence.push(`近 4 次记录中 ${negative} 次为负向状态`);
      return strategy({
        riskCode: "medium",
        level: "中度关注",
        mode: "action",
        tag: "建议连接他人",
        reason: "最近低睡眠或负面状态连续出现，建议联系可信任的人或校内支持资源。",
        desc: "本周低睡眠或负面状态连续出现，心晴会优先推荐低负担行动，并提示联系可信任的人。",
        evidence,
        explanation: "最近几次状态都有变化，可以先做小事，同时找人聊聊。",
        data,
        baseline
      });
    }
  
    if (signalPresent(latest, "mood") && NEGATIVE_MOODS.has(moodOf(latest))) {
      return strategy({
        riskCode: "normal",
        level: "普通波动",
        mode: "action",
        tag: "先做一件小事",
        reason: "现在更像日常压力波动，可以先做一件不费力的小事。",
        desc: "可以先试试呼吸放松、走动、写下来或早点休息中的一步。",
        evidence: [`当前情绪: ${moodOf(latest)}`],
        explanation: "目前没有出现需要马上求助或连续变差的提示，可以先做一个小行动。",
        data,
        baseline
      });
    }
  
    return strategy({
      riskCode: "stable",
      level: "稳定观察",
      mode: "action",
      tag: "保持记录",
      reason: "当前状态较平稳，继续保持记录和节奏观察。",
      desc: "当前状态较平稳，心晴会继续记录节奏变化，提醒你维持睡眠和连接感。",
      evidence: ["未触发危机词、连续低睡眠或连续负面状态规则"],
      explanation: "目前记录比较完整，也没有出现需要升级支持的提示。",
      data,
      baseline
    });
  }
  
  // 向后兼容：导出危险模式供外部使用。
  const dangerWords = DANGER_PATTERNS.map(({ re }) => re.source);
  const dangerPatterns = DANGER_PATTERNS;
  const safePhrases = SAFE_PHRASES;
  
  const PATHS = {
    anxious: ["breathe", "walk", "journal"],
    sad: ["breathe", "friend", "sleep"],
    tired: ["sleep", "breathe", "focus"],
    angry: ["breathe", "walk", "friend"],
    calm: ["focus", "journal", "walk"],
    happy: ["focus", "journal", "walk"]
  };
  
  const PATH_REASONS = {
    anxious: "先降低生理唤醒，再把注意力从压力源中移开。",
    sad: "先稳定状态，再建立连接，避免独自承受。",
    tired: "优先恢复身体电量，再恢复掌控感。",
    angry: "先把身体带离情绪中心，再表达。",
    calm: "顺势完成小目标，保留稳定节奏。",
    happy: "利用较好状态推进小目标，并留下正向记录。"
  };
  
  function completePath(chain, mood) {
    const base = PATHS[mood] || PATHS.calm;
    const fallback = ["breathe", "journal", "friend", "sleep", "walk", "focus"];
    return unique([...chain, ...base, ...fallback]).slice(0, 3);
  }
  
  function recommendPath(record, risk) {
    record = record || {};
    if (risk && (risk.level === "高风险" || risk.mode === "help" || risk.riskCode === "high")) {
      return {
        path: ["help"],
        reason: "遇到需要优先求助的情况，先联系一个真实的人。",
        reasons: ["出现危机信号"],
        mode: "help",
        risk: risk.level || "高风险",
        riskCode: "high",
        allowedActions: ["help"],
        blockedActions: ["breathe", "walk", "journal", "sleep", "focus", "friend", "self_check", "ordinary_intervention"],
        evidence: risk.evidence || ["出现危机信号"],
        explanation: "现在先联系一个真实的人，普通建议暂时暂停。"
      };
    }
  
    if (risk && (risk.level === "数据不足" || risk.mode === "ask" || risk.riskCode === "insufficient")) {
      return {
        path: ["ask"],
        reason: "记录还不够，先补充一点信息，再决定下一步。",
        reasons: ["过去记录还不够或有项目没填"],
        mode: "ask",
        risk: risk.level || "数据不足",
        riskCode: "insufficient",
        allowedActions: ["checkin", "ask"],
        blockedActions: ["ordinary_intervention", "self_check"],
        evidence: risk.evidence || ["数据不足"],
        explanation: "记录还不够，我先不急着下确定结论。"
      };
    }
  
    const mood = moodOf(record);
    const sleepHours = sleepOf(record);
    const socialScore = toNumber(record.socialScore ?? record.sc, 50);
    const energyLevel = record.energyLevel || "mid";
    const connectionNeed = record.connectionNeed || "ok";
    const reasons = [];
    let chain = (PATHS[mood] || PATHS.calm).slice();
  
    if (connectionNeed === "need" || socialScore < 25) {
      chain = ["friend", ...chain];
      reasons.push(connectionNeed === "need" ? "用户主动表达需要连接" : "社交连接偏低");
    } else if (connectionNeed === "avoid") {
      chain = [...chain.filter((id) => id !== "friend"), "friend"];
      reasons.push("用户暂时不想联系别人");
    }
  
    if (sleepHours > 0 && sleepHours < 5.2) {
      chain = ["sleep", "breathe", "journal", ...chain.filter((id) => id !== "focus")];
      reasons.push("睡眠明显不足");
    } else if (sleepHours > 0 && sleepHours < 6) {
      chain = mood === "tired" ? ["sleep", "breathe", ...chain] : ["breathe", "sleep", ...chain];
      reasons.push("睡眠低于 6 小时");
    }
  
    if (energyLevel === "low") {
      chain = ["breathe", "journal", "sleep", ...chain.filter((id) => id !== "focus")];
      reasons.push("精力偏低");
    } else if (energyLevel === "high" && ["happy", "calm"].includes(mood)) {
      chain = ["focus", ...chain];
      reasons.push("精力较高");
    }
  
    if (mood === "angry") {
      chain = ["walk", "breathe", ...chain];
      reasons.push("烦躁状态更适合先离开原地");
    }
  
    const path = completePath(chain, mood);
    return {
      path,
      reason: reasons.length
        ? `根据${reasons.join("、")}调整推荐顺序。`
        : PATH_REASONS[mood] || PATH_REASONS.calm,
      reasons: reasons.length ? unique(reasons) : ["当前状态较平稳"],
      mode: risk?.mode || "action",
      risk: risk?.level || "普通波动",
      riskCode: risk?.riskCode || "normal",
      allowedActions: risk?.allowedActions || ["checkin", "light_intervention", "contact_support"],
      blockedActions: risk?.blockedActions || [],
      evidence: risk?.evidence || [],
      explanation: risk?.explanation || PATH_REASONS[mood] || PATH_REASONS.calm
    };
  }
  
  const interventionLabels = {
    breathe: "先把身体降下来",
    walk: "离开原地 10 分钟",
    journal: "把脑子里的话倒出来",
    friend: "让一个人知道你",
    sleep: "今晚先收住",
    focus: "只做一件小事",
    ask: "补充最少的一项记录",
    help: "打开求助入口"
  };
  
  const BASELINE_WINDOW = 7;
  const MIN_BASELINE_SAMPLES = 3;
  const MIN_LEARNING_SAMPLES = 3;
  
  function round(value, digits = 0) {
    if (value === null || value === undefined || !Number.isFinite(Number(value))) return null;
    const factor = 10 ** digits;
    return Math.round(Number(value) * factor) / factor;
  }
  
  function median(values) {
    const sorted = values.filter((value) => Number.isFinite(Number(value))).map(Number).sort((a, b) => a - b);
    if (!sorted.length) return null;
    const middle = Math.floor(sorted.length / 2);
    return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2;
  }
  
  function percentDelta(current, baseline) {
    if (current === null || baseline === null || !baseline) return null;
    return round(((current - baseline) / baseline) * 100);
  }
  
  function confidenceLabel(score) {
    if (score >= 0.8) return "high";
    if (score >= 0.55) return "medium";
    return "low";
  }
  
  function confidenceText(label) {
    return label === "high" ? "较高" : label === "medium" ? "中等" : "较低";
  }
  
  function signalDescription(key, current, baseline, delta) {
    if (current === null) return `${SIGNAL_LABELS[key]}还没记录，不参与这次判断`;
    if (baseline === null) return `${SIGNAL_LABELS[key]}已经记录，我们还在了解你的平时状态`;
    if (key === "sleep" || key === "steps") {
      return `${SIGNAL_LABELS[key]}和你平时相比${delta >= 0 ? "多了" : "少了"} ${Math.abs(delta || 0)}%`;
    }
    return `${SIGNAL_LABELS[key]}和你平时相比${delta >= 0 ? "高了" : "低了"} ${Math.abs(delta || 0)}${key === "mood" ? "级" : "点"}`;
  }
  
  function emptyLearningRow(id) {
    return {
      id,
      count: 0,
      avgDelta: 0,
      weightedDelta: 0,
      eligible: false,
      status: "insufficient",
      explanation: "目前记录还不够，暂时看不出哪种做法更适合你"
    };
  }
  
  function isHighRiskEvent(event = {}) {
    return event.riskCode === "high" || event.mode === "help" || event.risk === "高风险" || event.level === "高风险";
  }
  
  function eventId(event = {}) {
    return event.interventionId || event.id || "";
  }
  
  function eventDelta(event = {}) {
    const delta = Number(event.delta);
    return Number.isFinite(delta) ? delta : null;
  }
  
  function calculatePersonalBaseline(records) {
    const safeRecords = normalizeRecords(records);
    const latest = safeRecords[safeRecords.length - 1] || {};
    const history = safeRecords.slice(0, -1).slice(-BASELINE_WINDOW);
    const currentData = dataCompletenessOf(latest);
    const historySignals = {};
    const stats = {};
    let readySignalCount = 0;
  
    for (const key of SIGNAL_KEYS) {
      const validHistory = history.filter((record) => signalPresent(record, key));
      const current = signalPresent(latest, key) ? signalValueOf(latest, key) : null;
      const baseline = median(validHistory.map((record) => signalValueOf(record, key)));
      const ready = validHistory.length >= MIN_BASELINE_SAMPLES;
      if (ready) readySignalCount += 1;
      const delta = current === null || baseline === null ? null : round(current - baseline, key === "mood" ? 1 : 0);
      const relativeDelta = percentDelta(current, baseline);
      historySignals[key] = {
        baseline: round(baseline, key === "mood" || key === "sleep" ? 1 : 0),
        current: round(current, key === "mood" || key === "sleep" ? 1 : 0),
        delta,
        relativeDelta,
        sampleCount: validHistory.length,
        ready,
        present: current !== null,
        source: signalSourceOf(latest, key),
        explanation: signalDescription(key, current, baseline, relativeDelta ?? delta)
      };
      stats[key] = historySignals[key];
    }
  
    const historyCoverage = SIGNAL_KEYS.reduce((sum, key) => {
      return sum + Math.min(1, (stats[key].sampleCount || 0) / MIN_BASELINE_SAMPLES);
    }, 0) / SIGNAL_KEYS.length;
    const depthCoverage = Math.min(1, history.length / MIN_BASELINE_SAMPLES);
    const confidenceScore = round(currentData.ratio * 0.5 + historyCoverage * 0.3 + depthCoverage * 0.2, 2);
    const confidence = confidenceLabel(confidenceScore);
    const coldStart = history.length < MIN_BASELINE_SAMPLES;
    const baselineReady = !coldStart && readySignalCount > 0;
  
    const base = {
      days: history.length,
      mood: stats.mood.baseline,
      sleep: stats.sleep.baseline,
      steps: stats.steps.baseline,
      social: stats.social.baseline
    };
    const delta = {
      mood: stats.mood.delta,
      sleepPct: stats.sleep.relativeDelta,
      stepsPct: stats.steps.relativeDelta,
      social: stats.social.delta
    };
  
    const flags = [];
    if (baselineReady) {
      if (stats.sleep.relativeDelta !== null && stats.sleep.relativeDelta <= -25) {
        flags.push(`睡眠比平时少 ${Math.abs(stats.sleep.relativeDelta)}%`);
      }
      if (stats.steps.relativeDelta !== null && stats.steps.relativeDelta <= -40) {
        flags.push(`活动比平时少 ${Math.abs(stats.steps.relativeDelta)}%`);
      }
      if (stats.social.delta !== null && stats.social.delta <= -20) {
        flags.push(`和人联系的感觉比平时低 ${Math.abs(stats.social.delta)} 点`);
      }
      if (stats.mood.delta !== null && stats.mood.delta <= -1) {
        flags.push(`情绪比平时低 ${Math.abs(stats.mood.delta).toFixed(1)} 级`);
      }
    }
  
    const currentInsufficient = currentData.available < 2;
    const level = coldStart || currentInsufficient
      ? "数据不足"
      : flags.length >= 2
        ? "明显偏离"
        : flags.length === 1
          ? "轻度偏离"
          : "接近基线";
    const title = level === "数据不足"
      ? "还在了解你的平时状态"
      : level === "接近基线"
        ? "今天和自己平时差不多"
        : level === "轻度偏离"
          ? "今天有一项和往常不太一样"
          : "今天有几项和往常不太一样";
    const desc = level === "数据不足"
      ? `现在有 ${currentData.available}/${currentData.required} 项记录，过去至少需要 ${MIN_BASELINE_SAMPLES} 条记录；暂时还不能充分判断。`
      : flags.length
        ? `${flags.join("；")}。这是和你过去的记录比较，不是和别人比较。`
        : "现在没有明显低于你最近几次记录的地方。";
  
    return {
      base,
      delta,
      flags,
      level,
      title,
      desc,
      status: coldStart ? "cold_start" : currentInsufficient ? "insufficient" : "ready",
      coldStart,
      baselineReady,
      historyRecords: history.length,
      readySignalCount,
      confidence,
      confidenceText: confidenceText(confidence),
      confidenceScore,
      dataCompleteness: currentData,
      signals: stats
    };
  }
  
  function summarizeInterventionFeedback(events = [], interventionStats = {}) {
    const grouped = {};
    const safeEvents = Array.isArray(events) ? events : [];
    safeEvents.forEach((event) => {
      const id = eventId(event);
      const delta = eventDelta(event);
      if (!id || id === "help" || delta === null || isHighRiskEvent(event) || event.eligibleForLearning === false) return;
      if (!grouped[id]) grouped[id] = [];
      grouped[id].push({ delta, event });
    });
  
    for (const [id, list] of Object.entries(grouped)) {
      let totalWeight = 0;
      let weightedSum = 0;
      list.forEach((item, index) => {
        const weight = 0.75 ** (list.length - index - 1);
        totalWeight += weight;
        weightedSum += item.delta * weight;
      });
      const count = list.length;
      const weightedDelta = totalWeight ? round(weightedSum / totalWeight, 1) : 0;
      grouped[id] = {
        id,
        count,
        avgDelta: round(list.reduce((sum, item) => sum + item.delta, 0) / count, 1),
        weightedDelta,
        eligible: count >= MIN_LEARNING_SAMPLES,
        status: count >= MIN_LEARNING_SAMPLES ? "ready" : "insufficient",
        explanation: count >= MIN_LEARNING_SAMPLES
          ? `根据你最近 ${count} 次相似记录，暂时看出一点规律；不代表因果或治疗效果`
          : "目前记录还不够，暂时看不出哪种做法更适合你"
      };
    }
  
    // 旧版只保存了汇总统计，无法证明其中没有高风险事件；只在没有事件明细时兼容读取。
    for (const [id, stat] of Object.entries(interventionStats || {})) {
      if (safeEvents.length) continue;
      if (grouped[id]) continue;
      const count = Number(stat?.count || 0);
      const totalDelta = Number(stat?.totalDelta || 0);
      if (!count) continue;
      const avgDelta = round(totalDelta / count, 1) || 0;
      grouped[id] = {
        id,
        count,
        avgDelta,
        weightedDelta: avgDelta,
        eligible: count >= MIN_LEARNING_SAMPLES,
        status: count >= MIN_LEARNING_SAMPLES ? "ready" : "insufficient",
        explanation: count >= MIN_LEARNING_SAMPLES
          ? `基于 ${count} 次同类反馈的个人倾向，不代表因果或治疗效果`
          : "样本不足，暂不形成个人倾向"
      };
    }
  
    return grouped;
  }
  
  function personalizeRecommendation(path, interventionStats = {}, events = []) {
    const learning = summarizeInterventionFeedback(events, interventionStats);
    return unique(path)
      .map((id, index) => {
        const stat = learning[id] || emptyLearningRow(id);
        const boost = stat.eligible
          ? Math.min(2.4, stat.count * 0.35) + Math.max(0, stat.weightedDelta) / 8
          : 0;
        return {
          id,
          score: index - boost,
          avgDelta: stat.weightedDelta,
          count: stat.count,
          eligible: stat.eligible
        };
      })
      .sort((a, b) => a.score - b.score)
      .map((item) => item.id);
  }

  global.MindPulseRules = {
    calculateRecoveryScore: calculateRecoveryScore,
    assessRisk: assessRisk,
    recommendPath: recommendPath,
    calculatePersonalBaseline: calculatePersonalBaseline,
    personalizeRecommendation: personalizeRecommendation,
    summarizeInterventionFeedback: summarizeInterventionFeedback,
    dataCompletenessOf: dataCompletenessOf,
    signalSnapshot: signalSnapshot,
    signalPresent: signalPresent,
    signalValueOf: signalValueOf,
    signalSourceOf: signalSourceOf,
    SIGNAL_KEYS: SIGNAL_KEYS,
    SIGNAL_LABELS: SIGNAL_LABELS,
    lowSleepDays: lowSleepDays,
    recentNegativeCount: recentNegativeCount,
    hasDangerSignal: hasDangerSignal,
    dangerPatterns: DANGER_PATTERNS,
    safePhrases: SAFE_PHRASES
  };
})(window);
